In [68]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix
from scipy.special import expit
import pandas as pd
import numpy as np

In [109]:
# Loading in trining data
training_data = pd.read_csv("songinput.csv")
target_output = [1,2,3,4,5,6,7,8,9,10,11,12]
training_data = training_data.drop(['no'], axis=1)

# Delete non-number columns
training_data = training_data.drop(['artist_name'], axis=1)
training_data = training_data.drop(['track_name'], axis=1)
training_data = training_data.drop(['track_id'], axis=1)
training_data = training_data.drop(['uri'], axis=1)
training_data = training_data.drop(['track_href'], axis=1)
training_data = training_data.drop(['analysis_url'], axis=1)
training_data = training_data.drop(['type'], axis=1)

training_data = training_data.drop(['popularity'], axis=1)
training_data = training_data.drop(['danceability'], axis=1)
training_data = training_data.drop(['energy'], axis=1)
training_data = training_data.drop(['key'], axis=1)
training_data = training_data.drop(['loudness'], axis=1)
training_data = training_data.drop(['mode'], axis=1)
training_data = training_data.drop(['speechiness'], axis=1)
training_data = training_data.drop(['acousticness'], axis=1)
training_data = training_data.drop(['instrumentalness'], axis=1)
training_data = training_data.drop(['liveness'], axis=1)
training_data = training_data.drop(['valence'], axis=1)
training_data = training_data.drop(['duration_ms'], axis=1)
training_data = training_data.drop(['time_signature'], axis=1)

training_data = np.asarray(training_data,dtype=np.float64)
training_count = len(training_data[:,0])
print(training_data)

[[171.005]
 [144.026]
 [116.971]
 [121.975]
 [110.962]
 [112.022]
 [128.977]
 [ 96.172]
 [116.735]
 [120.042]
 [101.085]
 [129.979]]


In [118]:
# Loading in validation data
validation_data = pd.read_csv("songinput2.csv")
validation_output = validation_data.no
validation_data = validation_data.drop(['no'], axis=1)

# Delete non-number columns
validation_data = validation_data.drop(['artist_name'], axis=1)
validation_data = validation_data.drop(['track_name'], axis=1)
validation_data = validation_data.drop(['track_id'], axis=1)
validation_data = validation_data.drop(['uri'], axis=1)
validation_data = validation_data.drop(['track_href'], axis=1)
validation_data = validation_data.drop(['analysis_url'], axis=1)
validation_data = validation_data.drop(['type'], axis=1)

validation_data = validation_data.drop(['popularity'], axis=1)
validation_data = validation_data.drop(['danceability'], axis=1)
validation_data = validation_data.drop(['energy'], axis=1)
validation_data = validation_data.drop(['key'], axis=1)
validation_data = validation_data.drop(['loudness'], axis=1)
validation_data = validation_data.drop(['mode'], axis=1)
validation_data = validation_data.drop(['speechiness'], axis=1)
validation_data = validation_data.drop(['acousticness'], axis=1)
validation_data = validation_data.drop(['instrumentalness'], axis=1)
validation_data = validation_data.drop(['liveness'], axis=1)
validation_data = validation_data.drop(['valence'], axis=1)
validation_data = validation_data.drop(['duration_ms'], axis=1)
validation_data = validation_data.drop(['time_signature'], axis=1)
validation_data = np.asarray(validation_data,dtype=np.float64)
validation_count = len(validation_data[:,0])
print(validation_data)

[[168.983]
 [ 91.019]]


In [110]:
#class sklearn.neural_network.MLPClassifier(hidden_layer_sizes=(100, ), 
# activation='relu', solver='adam', alpha=0.0001, batch_size='auto', 
# learning_rate='constant', learning_rate_init=0.001, power_t=0.5, max_iter=200, 
# shuffle=True, random_state=None, tol=0.0001, verbose=False, warm_start=False, 
# momentum=0.9, nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, 
# beta_1=0.9, beta_2=0.999, epsilon=1e-08, n_iter_no_change=10, max_fun=15000)

mlp = MLPClassifier(solver='lbfgs', activation='logistic',max_iter=1000)
mlp.fit(training_data,target_output)

mlp.classes_

/Users/lin_peihsuan/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
y_pred = mlp.predict(training_data)
print(y_pred)

[ 1  2  3  4  5  6 12  8  3  4 11 12]


In [112]:
print("Training set score: {}".format(mlp.score(training_data,target_output)))

Training set score: 0.75


In [124]:
print("Testing set score: {}".format(mlp.score(validation_data,validation_output)))

Testing set score: 0.5


In [119]:
print("Test set predicted ranking: {}".format(mlp.predict(validation_data)))

Test set predicted ranking: [1 8]


In [129]:
#probability to each label
print("Testing set score: {}".format(mlp.predict_proba(validation_data)))

Testing set score: [[8.79999875e-001 1.19952655e-001 1.76161865e-017 8.54705836e-011
  9.14368595e-029 9.79549099e-026 7.76709553e-006 1.87518901e-068
  6.67472438e-018 2.29792092e-013 1.90589603e-050 3.97021093e-005]
 [8.79875122e-124 3.30546748e-070 2.01921213e-017 9.15145849e-027
  2.52923589e-008 2.36971782e-010 7.42553112e-040 9.95077938e-001
  5.35742773e-017 5.02809379e-023 4.92203650e-003 4.17950223e-042]]


In [130]:
print(validation_output)

0    6
1    8
Name: no, dtype: int64


In [131]:
print(classification_report(validation_output,mlp.predict(validation_data)))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         1
           8       1.00      1.00      1.00         1

    accuracy                           0.50         2
   macro avg       0.33      0.33      0.33         2
weighted avg       0.50      0.50      0.50         2



/Users/lin_peihsuan/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/lin_peihsuan/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [132]:
from sklearn.metrics import accuracy_score
accuracy_score(validation_output,mlp.predict(validation_data))

0.5